const attackers = [
  {
    agent: 'Cypher',
    player: 'WaffleSlayer',
    rank: 'Immortal 2',
    overallWinPercentage: 54,
    gamesPlayedTotal: 65,
    winRateByAgent: 52,
    gamesPlayedByAgent: 28,
    kills: 24,
    deaths: 4,
    assists: 0,
  },
  {
    agent: 'Brimstone',
    player: 'Bobae',
    rank: 'Iron 1',
    overallWinPercentage: 33,
    gamesPlayedTotal: 22,
    winRateByAgent: 50,
    gamesPlayedByAgent: 10,
    kills: 2,
    deaths: 4,
    assists: 2,
  },
  {
    agent: 'Omen',
    player: 'Mikel',
    rank: 'Bronze 3 ',
    overallWinPercentage: 6,
    gamesPlayedTotal: 19,
    winRateByAgent: 45,
    gamesPlayedByAgent: 5,
    kills: 1,
    deaths: 5,
    assists: 4,
  },
  {
    agent: 'Breach',
    player: 'Urlan',
    rank: 'Silver 2',
    overallWinPercentage: 39,
    gamesPlayedTotal: 28,
    winRateByAgent: 33,
    gamesPlayedByAgent: 17,
    kills: 9,
    deaths: 4,
    assists: 5,
  },
  {
    agent: 'Sova',
    player: 'Serge',
    rank: 'Valorant',
    overallWinPercentage: 99,
    gamesPlayedTotal: 129,
    winRateByAgent: 99,
    gamesPlayedByAgent: 100,
    kills: 16,
    deaths: 0,
    assists: 4,
  },
];

const defenders = [
  {
    agent: 'Phoenix',
    player: 'BagelDestroyer',
    rank: 'Immortal 1',
    overallWinPercentage: 52,
    gamesPlayedTotal: 94,
    winRateByAgent: 40,
    gamesPlayedByAgent: 65,
    kills: 8,
    deaths: 13,
    assists: 0,
  },
  {
    agent: 'Brimstone',
    player: 'Samster',
    rank: 'Iron 1',
    overallWinPercentage: 21,
    gamesPlayedTotal: 34,
    winRateByAgent: 76,
    gamesPlayedByAgent: 12,
    kills: 4,
    deaths: 13,
    assists: 0,
  },
  {
    agent: 'Sage',
    player: 'Bob',
    rank: 'Bronze 3 ',
    overallWinPercentage: 39,
    gamesPlayedTotal: 22,
    winRateByAgent: 89,
    gamesPlayedByAgent: 17,
    kills: 2,
    deaths: 12,
    assists: 3,
  },
  {
    agent: 'Viper',
    player: 'Tim',
    rank: 'Silver 2',
    overallWinPercentage: 44,
    gamesPlayedTotal: 35,
    winRateByAgent: 34,
    gamesPlayedByAgent: 28,
    kills: 2,
    deaths: 12,
    assists: 1,
  },
  {
    agent: 'Omen',
    player: 'Ninja',
    rank: 'Gold 1',
    overallWinPercentage: 51,
    gamesPlayedTotal: 67,
    winRateByAgent: 45,
    gamesPlayedByAgent: 33,
    kills: 1,
    deaths: 13,
    assists: 0,
  },
];

export { attackers, defenders };
